import groovy.transform.Field

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'rust-report-printer'

pipeline {
    agent {
        kubernetes {
            defaultContainer 'rust-class'
            yaml '''
              spec:
                containers:
                  - name: rust-class
                    image: rustlang/rust:nightly-alpine
                    command: ["sleep", "infinity"]
                    resources:
                      requests:
                        cpu: 100m
                        memory: 64Mi
                      limits:
                        cpu: 1
                        memory: 128Mi
                  - name: node-class
                    image: node:18.11-alpine3.16
                    command: ["sleep", "infinity"]
                    resources:
                      requests:
                        cpu: 10m
                        memory: 8Mi
                      limits:
                        cpu: 1
                        memory: 16Mi
            '''
        }
    }

    environment {
      CARGO_UNSTABLE_SPARSE_REGISTRY = 'true'
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                  container('node-class') {
                    sh './report_generator.js'
                  }
                }
            }
        }

       stage('Install dependencies') {
           steps {
               dir(PROJECT_DIR) {
                   // if we are on alpine, we need to install musl-dev
                   sh 'apk add --no-cache musl-dev=1.2.2-r7'
               }
           }
       }

        stage('Build') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'cargo build --locked'
                }
            }
        }

        // Oh no, we can't perform regular Docker Builds on Kubernetes
        /*
        stage('Build Image') {
            environment {
                DOCKER_BUILDKIT = "1"
            }
            steps {
                dir(PROJECT_DIR) {
                    sh 'docker build -t super-report-printer:v0.1.0 .'
                }
            }
        }
         */
    }
}
